### ISSUE TITLE
Install mroonga without changing mysql

### ISSUE THREAD

**Issue by onlyone0001** [mroonga/mroonga#120]
I have Percona server installed and when i try to install mroonga via apt following the instructions, it removes my server with an older mysql installation.  

Can i install without mroonga without your mysql or mariadb version?

(You should remove the -Y from $ sudo apt-get install -y -V mysql-server-mroonga)

**Comment by kou** [comment]
What is your platform? Ubuntu 16.10?

**Comment by onlyone0001** [comment]
Ubuntu 14.04

**Comment by kou** [comment]
We never provide Mroonga package for Percona server on Ubuntu 14.04.
Because Ubuntu 14.04 doesn't ship Percona server.

(We may provide Mroonga package for Ubuntu 16.04 or later because Ubuntu 16.04 or later ship Percona server.)

You need to install Mroonga from source. See http://mroonga.org/docs/install/others.html#build-from-source for details.
