### ISSUE TITLE
unmet dependencies 9.07 with 10.3.17 MariaDB

### ISSUE THREAD

**Issue by bizlevel** [mroonga/mroonga#274]
I try install mroonga on this manual http://mroonga.org/docs/install/debian.html#buster-mariadb

But it is hardly depend from 10.3.15 MariaDB and no work with 10.3.17 (
But here - http://mroonga.org/en/blog/2019/08/29/mroonga-9.07.html
I can see that **Added support for MariaDB 10.1.41, 10.2.26, 10.3.17, and 10.4.7.**
Hm very strange - because not worked it.
How to resolve it?

```
root@cz:/etc/apt/sources.list.d# apt install -V mariadb-server-10.3-mroonga
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mariadb-server-10.3-mroonga : Depends: mariadb-server-10.3 (= 1:10.3.15-1) but 1:10.3.17-0+deb10u1 is to be installed
                               Depends: mariadb-server-core-10.3 (= 1:10.3.15-1) but 1:10.3.17-0+deb10u1 is to be installed
E: Unable to correct problems, you have held broken packages.

root@cz:/etc/apt/sources.list.d# apt install mariadb-server-core-10.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
mariadb-server-core-10.3 is already the newest version (1:10.3.17-0+deb10u1).
mariadb-server-core-10.3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@cz:/etc/apt/sources.list.d#
root@cz:/etc/apt/sources.list.d# apt policy mariadb-server
mariadb-server:
  Installed: 1:10.3.17-0+deb10u1
  Candidate: 1:10.3.17-0+deb10u1
  Version table:
 *** 1:10.3.17-0+deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        500 http://mirror.hetzner.de/debian/packages buster/main amd64 Packages
        100 /var/lib/dpkg/status
root@cz:/etc/apt/sources.list.d#

```

**Comment by kenhys** [comment]
@bizlevel 
Hi, Mroonga storage engine  is built with specific version of MariaDB, so if newer version of MariaDB is released, it requires to rebuild. Thus, in this case, unmet dependency error is occurred because of Debian buster 10.1 point release. [1]

[1] https://www.debian.org/releases/stable/errata#pointrelease 

Since Debian buster 10.1 point release, MariaDB is upgraded from 10.3.15 to 10.3.17-0+deb10u1, so dependency is broken (This is intended behavior because there is no guaranteed that it wold work with newer version)

I'll rebuild and upload package for it. could you wait for a while, sorry for inconvenience.

**Comment by kenhys** [comment]
@bizlevel uploaded 9.07-2. The following commands will fix this issue.
Thank you for reporting!

```
% sudo apt update
% sudo apt install -y -V mariadb-server-10.3-mroonga
```
