### ISSUE TITLE
Wrapper Mode Lost Connection -TokuDB

### ISSUE THREAD

**Issue by onlyone0001** [mroonga/mroonga#49]
As also expressed here (http://ocelot.ca/blog/blog/2014/12/), wrapper mode with TokuDB is not working, as of MariaDB 10.0.17.

**Comment by kou** [comment]
Thanks for your report.

We need to support table/field/index options https://mariadb.com/kb/en/mariadb/engine-defined-new-tablefieldindex-attributes/ in wrapper mode.

**Comment by onlyone0001** [comment]
Will it be supported soon / is it on to-do list? 
If not, would it be possible to use mroonga_dry_write (or something else) to not use mroonga for storage but for text search?

**Comment by kou** [comment]
It's on to-do list. Sorry.

You can use TokuDB and Mroonga like wrapper mode by master-slave architecture.

- Create a table with TokuDB on master.
- Create a slave for the master.
- Run `ALTER TABLE ENGINE=Mroonga` on slave.
- Search by Mroonga on slave.

I hope that this technique helps you.

**Comment by onlyone0001** [comment]
Thanks for the tip!
Though it's not related to this issue, i have a question: On my test database, mroonga (in storage mode, without compression, dropped indexes) takes 2.5 times more storage than InnoDB. Is this normal?

**Comment by kou** [comment]
> Though it's not related to this issue, i have a question: On my test database, mroonga (in storage mode, without compression, dropped indexes) takes 3 times more storage than InnoDB. Is this normal?

Mroonga's storage implementation uses almost same or more size of the original data. Because Mroonga's storage implementation uses fixed size boxes for small data (<= 4KiB) and variable size boxes for large data. Some dead spaces are occurred in these boxes. So more size of the original data are used.

And Mroonga allocates large file size at a time to reduce small file size expansions. It means that most Mroonga's data files are sparse.

The following article describes about related things but it's written in Japanese. Sorry...
http://www.clear-code.com/blog/2014/3/13.html

**Comment by kou** [comment]
> Is this normal?

Sorry. I forgot to write short answer. Maybe it's normal.

**Comment by onlyone0001** [comment]
I made further tests. Mroonga uses more space than InnoDB due to early and large file allocation, but the difference decreases with more data.
By the way, MariaDB 10.0.17 version apparently doesn't support lz4 compression, only zlib.
Are you planning to introduce page compression instead of column compression?

**Comment by kou** [comment]
> By the way, MariaDB 10.0.17 version apparently doesn't support lz4 compression, only zlib.

MariaDB package doesn't enable lz4 support but you can use lz4 if you build by yourself. Please contact MariaDB developers to enable it because MariaDB developers create package.

> Are you planning to introduce page compression instead of column compression?

No. There is no plan to introduce page compression. Why do you want page compression? Column compression isn't enough?

**Comment by onlyone0001** [comment]
Page compression seems to help with io and can produce higher compression ratios due to higher data size used for compression. Furthermore, in some cases such as this (column a: aaa, column b: bbb, column c: aaa + bbb + ccc), it would have more data to compress.

**Comment by kou** [comment]
It seems that page compression isn't suitable for Mroonga (Groonga) IO implementation.

Mroonga (Groonga) uses `mmap()` to access (read/write) data. It doesn't use `read()` and `write()`. Mroonga doesn't have buffer pool. Mroonga doesn't use page unit read/write.

Page compression will produce higher compression ratio rather than column compression. But decompression and recompression aren't occurred so much in full text search? Many indexed search like range search will use sequential access. So page compression will be comfortable. But full text search will use randam access to read data. Random access will touch many data in multiple pages. Does it cause decompression and recompression?

**Comment by kou** [comment]
> We need to support table/field/index options https://mariadb.com/kb/en/mariadb/engine-defined-new-tablefieldindex-attributes/ in wrapper mode.

I've implemented it. Mroonga 5.04, will be released at 2015-06-29, will be able to work with TokuDB.

**Comment by onlyone0001** [comment]
Spectacular!
