### ISSUE TITLE
data folder and ini file missing in winx64.zip

### ISSUE THREAD

**Issue by aki360P** [mroonga/mroonga#827]
### What happened?

[mariadb-10.11.9-with-mroonga-14.08-winx64.zip](https://github.com/mroonga/mroonga/releases/download/v14.08/mariadb-10.11.9-with-mroonga-14.08-winx64.zip) does not contain "data" folder or ".ini" file. 

Can you check the release procedure?

### How to reproduce it

release zip (above mroonga 12.11 version zip for windows)

### Additional context

mariadb-10.4.27-with-mroonga-12.10-winx64.zip までは問題なく，コマンドプロンプトより，`mysqld.exe --defaults-file=.\my.ini --console` で起動できます。少し間が空いてリリースされている12.11以降は，dataフォルダやその中にあるデータベース初期ファイル，iniファイルがなくて起動に失敗します。（古いバージョンのiniファイルやダミーの空フォルダ作るとエラーメッセージが変わるので，単にdataフォルダがrelese zipに含まれていないのが問題と思われます）
ご確認よろしくお願いします。

**Comment by kou** [comment]
The `data` directory in a package was included just for easy to try purpose. It's not expected to be used for real use.
Each user should create a new `data` directory by [`mariadb_install_db.exe`](https://mariadb.com/kb/en/mariadb-install-db-exe/) on installed environment instead of reusing the `data` directory in a package.

Because of the above reason, we removed the `data` directory from Windows packages by https://github.com/mroonga/mroonga/commit/fc81a249f363d2ebba4dd334356dee02e2911b44 .

**Comment by aki360P** [comment]
Thank you for information. It works!

So, the install note for windwos zip should be...

1. Extract zip to C:/mariadb-10.11.9-with-mroonga-14.08
2. With administrator command prompt, create database, register as a service
    cd C:/mariadb-10.11.9-with-mroonga-14.08/bin
    mariadb-install-db.exe --datadir=C:/mariadb-10.11.9-with-mroonga-14.08/data --service=MyDB  --password=secret

or
without service registeration 

1. Extract zip to C:/mariadb-10.11.9-with-mroonga-14.08
2. With administrator command prompt, create initial database
    cd C:/mariadb-10.11.9-with-mroonga-14.08/bin
    mariadb-install-db.exe --datadir=C:/mariadb-10.11.9-with-mroonga-14.08/data --password=secret
3. Start server command
    mysqld.exe --defaults-file=C:/mariadb-10.11.9-with-mroonga-14.08/data/my.ini --console

ほかの人もつまずくかもしれないので，できればmroongaホームページのinstall noteも更新お願いします

**Comment by kou** [comment]
更新しましたー

**Comment by kou** [comment]
あ、mroonga.orgの方が更新されるのは次のリリースのときになります。
